In [4]:
import yfinance as yf
import baostock as bs
import pandas as pd
from tqdm import tqdm
import time
import os
import random
import akshare as ak

In [5]:
import os
proxy = 'http://127.0.0.1:7890' # 代理设置，此处修改
os.environ['HTTP_PROXY'] = proxy
os.environ['HTTPS_PROXY'] = proxy

In [3]:
# 彻底禁掉代理（见上一节）
for v in ("HTTP_PROXY","HTTPS_PROXY","http_proxy","https_proxy"):
    os.environ.pop(v, None)

# 获取港股

In [3]:
# 1. 拉取港股实时列表
df_hk = ak.stock_hk_spot_em()
# akshare 返回的代码列叫 '代码'
# 格式化成 yfinance 识别的形式："0700" → "0700.HK"
tickers = df_hk['代码'].apply(lambda x: f"{x}.HK").tolist()

# （可选）过滤掉少量格式不标准的，确保都是 4 位数字开头
tickers = [t for t in tickers if t.split('.')[0].isdigit()]

print(f"共拿到 {len(tickers)} 只港股代码示例：", tickers[:5])
codes = df_hk['代码'].tolist()

  0%|          | 0/45 [00:00<?, ?it/s]

共拿到 4583 只港股代码示例： ['01152.HK', '01667.HK', '02442.HK', '08537.HK', '00202.HK']

In [4]:
tickers

['01152.HK',
 '01667.HK',
 '02442.HK',
 '08537.HK',
 '00202.HK',
 '08249.HK',
 '00602.HK',
 '01080.HK',
 '02400.HK',
 '01967.HK',
 '00767.HK',
 '00265.HK',
 '01228.HK',
 '01938.HK',
 '06113.HK',
 '08340.HK',
 '02415.HK',
 '00508.HK',
 '01237.HK',
 '02170.HK',
 '08223.HK',
 '01797.HK',
 '08100.HK',
 '02182.HK',
 '02427.HK',
 '02350.HK',
 '01812.HK',
 '00348.HK',
 '06998.HK',
 '08277.HK',
 '00323.HK',
 '01968.HK',
 '01672.HK',
 '06622.HK',
 '00093.HK',
 '02558.HK',
 '01428.HK',
 '02500.HK',
 '01432.HK',
 '01286.HK',
 '08366.HK',
 '08153.HK',
 '00568.HK',
 '06918.HK',
 '00865.HK',
 '00899.HK',
 '01631.HK',
 '09606.HK',
 '08176.HK',
 '01741.HK',
 '01947.HK',
 '02522.HK',
 '06855.HK',
 '08456.HK',
 '00075.HK',
 '02696.HK',
 '02168.HK',
 '00915.HK',
 '02340.HK',
 '08232.HK',
 '00983.HK',
 '01473.HK',
 '03728.HK',
 '00619.HK',
 '09968.HK',
 '01150.HK',
 '00799.HK',
 '08480.HK',
 '00326.HK',
 '02157.HK',
 '01020.HK',
 '09930.HK',
 '01877.HK',
 '08106.HK',
 '00320.HK',
 '08040.HK',
 '01022.HK',
 '02545.HK',
 '02616.HK',
 '00695.HK',
 '02310.HK',
 '00583.HK',
 '02162.HK',
 '08156.HK',
 '01676.HK',
 '06660.HK',
 '00557.HK',
 '02559.HK',
 '09788.HK',
 '06968.HK',
 '07788.HK',
 '03836.HK',
 '00422.HK',
 '01647.HK',
 '06996.HK',
 '00108.HK',
 '02066.HK',
 '06038.HK',
 '01500.HK',
 '00932.HK',
 '01661.HK',
 '00085.HK',
 '08059.HK',
 '02221.HK',
 '02216.HK',
 '02314.HK',
 '01675.HK',
 '01991.HK',
 '02100.HK',
 '08299.HK',
 '00376.HK',
 '00984.HK',
 '00846.HK',
 '01653.HK',
 '02552.HK',
 '00242.HK',
 '06058.HK',
 '00305.HK',
 '02567.HK',
 '06628.HK',
 '00547.HK',
 '08080.HK',
 '02142.HK',
 '09969.HK',
 '01304.HK',
 '02250.HK',
 '09799.HK',
 '02590.HK',
 '01940.HK',
 '01433.HK',
 '02012.HK',
 '00302.HK',
 '01132.HK',
 '00076.HK',
 '00200.HK',
 '02225.HK',
 '00587.HK',
 '00285.HK',
 '08645.HK',
 '00111.HK',
 '02181.HK',
 '00519.HK',
 '08222.HK',
 '00368.HK',
 '01712.HK',
 '01148.HK',
 '08021.HK',
 '01129.HK',
 '01801.HK',
 '08017.HK',
 '00880.HK',
 '02256.HK',
 '00086.HK',
 '06610.HK',
 '00259.HK',
 '00655.HK',
 '09939.HK',
 '00493.HK',
 '01763.HK',
 '07799.HK',
 '01250.HK',
 '01486.HK',
 '01900.HK',
 '00712.HK',
 '00434.HK',
 '02603.HK',
 '03603.HK',
 '01628.HK',
 '00876.HK',
 '00745.HK',
 '00230.HK',
 '03738.HK',
 '09926.HK',
 '01340.HK',
 '00497.HK',
 '08379.HK',
 '02110.HK',
 '01427.HK',
 '02122.HK',
 '00022.HK',
 '09869.HK',
 '06185.HK',
 '02689.HK',
 '00553.HK',
 '82388.HK',
 '01739.HK',
 '01167.HK',
 '09995.HK',
 '02410.HK',
 '00670.HK',
 '06609.HK',
 '00620.HK',
 '02033.HK',
 '01569.HK',
 '03395.HK',
 '06990.HK',
 '00717.HK',
 '02105.HK',
 '02388.HK',
 '08229.HK',
 '02298.HK',
 '01773.HK',
 '00496.HK',
 '01119.HK',
 '08238.HK',
 '08545.HK',
 '06119.HK',
 '01164.HK',
 '00521.HK',
 '06100.HK',
 '01272.HK',
 '02171.HK',
 '01916.HK',
 '06088.HK',
 '09688.HK',
 '00039.HK',
 '00027.HK',
 '08471.HK',
 '01062.HK',
 '03087.HK',
 '02126.HK',
 '80992.HK',
 '01655.HK',
 '01111.HK',
 '01530.HK',
 '00258.HK',
 '01621.HK',
 '09990.HK',
 '01172.HK',
 '00931.HK',
 '00992.HK',
 '00162.HK',
 '01541.HK',
 '87001.HK',
 '02804.HK',
 '00149.HK',
 '00995.HK',
 '01449.HK',
 '03046.HK',
 '01578.HK',
 '02185.HK',
 '02457.HK',
 '00095.HK',
 '00630.HK',
 '01128.HK',
 '03004.HK',
 '02668.HK',
 '02209.HK',
 '02722.HK',
 '02155.HK',
 '02509.HK',
 '00347.HK',
 '01903.HK',
 '01927.HK',
 '00613.HK',
 '01069.HK',
 '01776.HK',
 '09660.HK',
 '03908.HK',
 '02172.HK',
 '01097.HK',
 '01582.HK',
 '08540.HK',
 '09804.HK',
 '02425.HK',
 '01870.HK',
 '00999.HK',
 '01767.HK',
 '03068.HK',
 '03009.HK',
 '03301.HK',
 '03939.HK',
 '00777.HK',
 '00989.HK',
 '08071.HK',
 '00042.HK',
 '00306.HK',
 '06869.HK',
 '00405.HK',
 '01328.HK',
 '00856.HK',
 '02799.HK',
 '00581.HK',
 '09996.HK',
 '00727.HK',
 '03958.HK',
 '07261.HK',
 '00684.HK',
 '02728.HK',
 '09046.HK',
 '01629.HK',
 '03069.HK',
 '07766.HK',
 '06979.HK',
 '00682.HK',
 '09069.HK',
 '02235.HK',
 '02282.HK',
 '00998.HK',
 '03179.HK',
 '00366.HK',
 '08422.HK',
 '01708.HK',
 '00763.HK',
 '01093.HK',
 '03389.HK',
 '08631.HK',
 '02252.HK',
 '06127.HK',
 '01477.HK',
 '02455.HK',
 '00063.HK',
 '06613.HK',
 '02511.HK',
 '83046.HK',
 '00723.HK',
 '01208.HK',
 '06881.HK',
 '01988.HK',
 '02076.HK',
 '06929.HK',
 '03339.HK',
 '01651.HK',
 '06098.HK',
 '01112.HK',
 '01316.HK',
 '81299.HK',
 '00546.HK',
 '00710.HK',
 '07266.HK',
 '09680.HK',
 '02297.HK',
 '00329.HK',
 '00559.HK',
 '09626.HK',
 '03839.HK',
 '00726.HK',
 '00245.HK',
 '00107.HK',
 '01952.HK',
 '01508.HK',
 '06066.HK',
 '01456.HK',
 '02227.HK',
 '02643.HK',
 '01606.HK',
 '01238.HK',
 '03788.HK',
 '00968.HK',
 '09179.HK',
 '02228.HK',
 '00811.HK',
 '01177.HK',
 '01599.HK',
 '00691.HK',
 '00270.HK',
 '03174.HK',
 '03399.HK',
 '01216.HK',
 '00013.HK',
 '09009.HK',
 '01000.HK',
 '06682.HK',
 '02555.HK',
 '01299.HK',
 '01359.HK',
 '08163.HK',
 '01319.HK',
 '01526.HK',
 '00171.HK',
 '06839.HK',
 '00204.HK',
 '00425.HK',
 '08629.HK',
 '00576.HK',
 '00805.HK',
 '00871.HK',
 '01029.HK',
 '01725.HK',
 '00788.HK',
 '06818.HK',
 '03918.HK',
 '02236.HK',
 '08622.HK',
 '00697.HK',
 '06806.HK',
 '00950.HK',
 '00163.HK',
 '09900.HK',
 '01375.HK',
 '00152.HK',
 '07311.HK',
 '00272.HK',
 '09890.HK',
 '01476.HK',
 '01928.HK',
 '02680.HK',
 '00853.HK',
 '06199.HK',
 '02566.HK',
 '01064.HK',
 '02255.HK',
 '00862.HK',
 '02203.HK',
 '00327.HK',
 '02628.HK',
 '00081.HK',
 '02359.HK',
 '02866.HK',
 '00560.HK',
 '00675.HK',
 '01059.HK',
 '08128.HK',
 '02309.HK',
 '00863.HK',
 '00293.HK',
 '02137.HK',
 '08476.HK',
 '00595.HK',
 '00354.HK',
 '03709.HK',
 '00373.HK',
 '01263.HK',
 '00893.HK',
 '08519.HK',
 '00055.HK',
 '00894.HK',
 '08196.HK',
 '08429.HK',
 '01555.HK',
 '00317.HK',
 '09899.HK',
 '01288.HK',
 '01268.HK',
 '00952.HK',
 '02013.HK',
 '09959.HK',
 '02880.HK',
 '02772.HK',
 '01891.HK',
 '00010.HK',
 '02569.HK',
 '03158.HK',
 '00365.HK',
 '00383.HK',
 '00806.HK',
 '00346.HK',
 '02018.HK',
 '01905.HK',
 '03678.HK',
 '01113.HK',
 '03405.HK',
 '02778.HK',
 '09766.HK',
 '01075.HK',
 '01717.HK',
 '01568.HK',
 '02129.HK',
 '03931.HK',
 '06822.HK',
 '00321.HK',
 '01691.HK',
 '02601.HK',
 '03993.HK',
 '00048.HK',
 '02389.HK',
 '06196.HK',
 '00179.HK',
 '00757.HK',
 '09868.HK',
 '06955.HK',
 '09992.HK',
 '01257.HK',
 '00165.HK',
 '03132.HK',
 '00768.HK',
 '01488.HK',
 '83069.HK',
 '06939.HK',
 '01114.HK',
 '01698.HK',
 '06099.HK',
 '03360.HK',
 '08220.HK',
 '08612.HK',
 '00667.HK',
 '02283.HK',
 '03882.HK',
 '01786.HK',
 '06663.HK',
 '00028.HK',
 '00151.HK',
 '02820.HK',
 '01157.HK',
 '00718.HK',
 '01339.HK',
 '02007.HK',
 '00662.HK',
 '06178.HK',
 '00753.HK',
 '03396.HK',
 '09820.HK',
 '00598.HK',
 '06963.HK',
 '01053.HK',
 '02600.HK',
 '01733.HK',
 '00926.HK',
 '01419.HK',
 '09919.HK',
 '03347.HK',
 '02150.HK',
 '03056.HK',
 '00731.HK',
 '01102.HK',
 '02022.HK',
 '02660.HK',
 '02576.HK',
 '01816.HK',
 '01030.HK',
 '02239.HK',
 '01251.HK',
 '01280.HK',
 '00861.HK',
 '08423.HK',
 '00833.HK',
 '00884.HK',
 '08657.HK',
 '03650.HK',
 '06655.HK',
 '06608.HK',
 '00511.HK',
 '06639.HK',
 '01933.HK',
 '00322.HK',
 '01338.HK',
 '00119.HK',
 '02487.HK',
 '00640.HK',
 '01024.HK',
 '00290.HK',
 '02453.HK',
 '02208.HK',
 '00160.HK',
 '01368.HK',
 '02536.HK',
 '02886.HK',
 '03034.HK',
 '81024.HK',
 '00558.HK',
 '02232.HK',
 '03866.HK',
 '01527.HK',
 '08043.HK',
 '01276.HK',
 '09911.HK',
 '06198.HK',
 '00371.HK',
 '09698.HK',
 '02230.HK',
 '00345.HK',
 '06158.HK',
 '00467.HK',
 '02899.HK',
 '06030.HK',
 '08529.HK',
 '00157.HK',
 '03006.HK',
 '02016.HK',
 '00314.HK',
 '03454.HK',
 '03877.HK',
 '00900.HK',
 '01729.HK',
 '01398.HK',
 '02197.HK',
 '02551.HK',
 '01620.HK',
 '07233.HK',
 '01378.HK',
 '01496.HK',
 '02563.HK',
 '01060.HK',
 '00191.HK',
 '00535.HK',
 '00868.HK',
 '00211.HK',
 '01709.HK',
 '01833.HK',
 '00912.HK',
 '09989.HK',
 '03185.HK',
 '01963.HK',
 '03988.HK',
 '00732.HK',
 '02111.HK',
 '09922.HK',
 '01347.HK',
 '00683.HK',
 '01907.HK',
 '01610.HK',
 '02814.HK',
 '01617.HK',
 '03319.HK',
 '09676.HK',
 '83455.HK',
 '03328.HK',
 '02598.HK',
 '09074.HK',
 '00185.HK',
 '01662.HK',
 '01025.HK',
 '00970.HK',
 '08512.HK',
 '02342.HK',
 '01961.HK',
 '09814.HK',
 '02429.HK',
 '08371.HK',
 '00956.HK',
 '01071.HK',
 '01747.HK',
 '01730.HK',
 '01379.HK',
 '01756.HK',
 '00251.HK',
 '03692.HK',
 '00819.HK',
 '00631.HK',
 '00257.HK',
 '02507.HK',
 '03116.HK',
 '06188.HK',
 '03868.HK',
 '01908.HK',
 '01955.HK',
 '09893.HK',
 '01301.HK',
 '03306.HK',
 '01055.HK',
 '01085.HK',
 '09455.HK',
 '01523.HK',
 '08282.HK',
 '00169.HK',
 '02096.HK',
 '00752.HK',
 '01313.HK',
 '03074.HK',
 '02617.HK',
 '00363.HK',
 '03147.HK',
 '03686.HK',
 '02192.HK',
 '00517.HK',
 '03455.HK',
 '02858.HK',
 '06823.HK',
 '03938.HK',
 '02382.HK',
 '00590.HK',
 '03036.HK',
 '02167.HK',
 '01247.HK',
 '00177.HK',
 '08037.HK',
 '09834.HK',
 '03453.HK',
 '01848.HK',
 '09311.HK',
 '00564.HK',
 '00525.HK',
 '02138.HK',
 '00991.HK',
 '02339.HK',
 '00168.HK',
 '03898.HK',
 '06603.HK',
 '01788.HK',
 '00401.HK',
 '06601.HK',
 '00144.HK',
 '02459.HK',
 '06669.HK',
 '00626.HK',
 '00855.HK',
 '01133.HK',
 '02376.HK',
 '00822.HK',
 '01141.HK',
 '00951.HK',
 '03838.HK',
 '00551.HK',
 '00808.HK',
 '01995.HK',
 '06812.HK',
 '00743.HK',
 '00616.HK',
 '02233.HK',
 '02810.HK',
 '02834.HK',
 '82020.HK',
 '00201.HK',
 '02356.HK',
 '03718.HK',
 '00677.HK',
 '09086.HK',
 '01898.HK',
 '07262.HK',
 '03382.HK',
 '01529.HK',
 '02347.HK',
 '08611.HK',
 '03171.HK',
 '01138.HK',
 '03086.HK',
 '03669.HK',
 '02518.HK',
 '80700.HK',
 '00591.HK',
 '09159.HK',
 '80020.HK',
 '00440.HK',
 '02097.HK',
 '01521.HK',
 '03442.HK',
 '00148.HK',
 '01799.HK',
 '03172.HK',
 '01393.HK',
 '09991.HK',
 '01836.HK',
 '00556.HK',
 '00610.HK',
 '01317.HK',
 '02888.HK',
 '00966.HK',
 '01751.HK',
 '00459.HK',
 '00358.HK',
 '01033.HK',
 '00656.HK',
 '01880.HK',
 '00023.HK',
 '09658.HK',
 '03195.HK',
 '02586.HK',
 '00116.HK',
 '01072.HK',
 '02465.HK',
 '00510.HK',
 '01766.HK',
 '06666.HK',
 '09987.HK',
 '82830.HK',
 '06868.HK',
 '03759.HK',
 '00227.HK',
 '02031.HK',
 '00412.HK',
 '03412.HK',
 '02015.HK',
 '02482.HK',
 '01088.HK',
 '01083.HK',
 '02263.HK',
 '00939.HK',
 '02020.HK',
 '02251.HK',
 '07200.HK',
 '02688.HK',
 '03618.HK',
 '02368.HK',
 '03134.HK',
 '02009.HK',
 '01001.HK',
 '02411.HK',
 '01873.HK',
 '00241.HK',
 '02269.HK',
 '02331.HK',
 '02319.HK',
 '09896.HK',
 '03156.HK',
 '01718.HK',
 '07226.HK',
 '82331.HK',
 '08160.HK',
 '01258.HK',
 '01860.HK',
 '09107.HK',
 '00267.HK',
 '09156.HK',
 '01273.HK',
 '00700.HK',
 '06138.HK',
 '02699.HK',
 '02570.HK',
 '03698.HK',
 '01499.HK',
 '00229.HK',
 '00300.HK',
 '01373.HK',
 '00392.HK',
 '03969.HK',
 '09999.HK',
 '03165.HK',
 '02328.HK',
 '00882.HK',
 '02377.HK',
 '00588.HK',
 '09181.HK',
 '01057.HK',
 '01650.HK',
 '03606.HK',
 '03998.HK',
 '00038.HK',
 '03181.HK',
 '01516.HK',
 '00008.HK',
 '01909.HK',
 '09810.HK',
 '82823.HK',
 '09747.HK',
 '02877.HK',
 '00123.HK',
 '02878.HK',
 '00754.HK',
 '03150.HK',
 '06886.HK',
 '01601.HK',
 '02823.HK',
 '03383.HK',
 '02506.HK',
 '00001.HK',
 '83111.HK',
 '06862.HK',
 '03363.HK',
 '00775.HK',
 '00315.HK',
 '03110.HK',
 '00294.HK',
 '01186.HK',
 '01920.HK',
 '01050.HK',
 '03470.HK',
 '01364.HK',
 '01052.HK',
 '02279.HK',
 '03896.HK',
 '83146.HK',
 '09070.HK',
 '08188.HK',
 '09686.HK',
 '00312.HK',
 '07288.HK',
 '00037.HK',
 '09839.HK',
 '09979.HK',
 '08027.HK',
 '03021.HK',
 '01895.HK',
 '08219.HK',
 '00536.HK',
 '00696.HK',
 '06676.HK',
 '02338.HK',
 '00450.HK',
 '00611.HK',
 '09446.HK',
 '03190.HK',
 '03020.HK',
 '01713.HK',
 '01481.HK',
 '02801.HK',
 '00533.HK',
 '01308.HK',
 '00390.HK',
 '03410.HK',
 '83189.HK',
 '01823.HK',
 '06093.HK',
 '83403.HK',
 '03182.HK',
 '09146.HK',
 '86618.HK',
 '02257.HK',
 '03601.HK',
 '03153.HK',
 '02381.HK',
 '02839.HK',
 '82839.HK',
 '09668.HK',
 '03318.HK',
 '02386.HK',
 '01330.HK',
 '00772.HK',
 '83168.HK',
 '82822.HK',
 '02806.HK',
 '06618.HK',
 '00653.HK',
 '83188.HK',
 '03432.HK',
 '01278.HK',
 '01910.HK',
 '02727.HK',
 '00215.HK',
 '00909.HK',
 '02843.HK',
 '83010.HK',
 '03189.HK',
 '03422.HK',
 '03443.HK',
 '03145.HK',
 '02038.HK',
 '83038.HK',
 '01855.HK',
 '80175.HK',
 '08495.HK',
 '01681.HK',
 '00689.HK',
 '01668.HK',
 '09923.HK',
 '09887.HK',
 '03111.HK',
 '03188.HK',
 '03413.HK',
 '03003.HK',
 '01658.HK',
 '01410.HK',
 '01999.HK',
 '09403.HK',
 '03368.HK',
 '02803.HK',
 '02830.HK',
 '01475.HK',
 '00435.HK',
 '01415.HK',
 '03039.HK',
 '01066.HK',
 '01532.HK',
 '03433.HK',
 '09803.HK',
 '09115.HK',
 '03040.HK',
 '03029.HK',
 '03070.HK',
 '00552.HK',
 '82843.HK',
 '03800.HK',
 '09188.HK',
 '01635.HK',
 '02068.HK',
 '06969.HK',
 '09633.HK',
 '01448.HK',
 '08050.HK',
 '00728.HK',
 '02571.HK',
 '03033.HK',
 '03012.HK',
 '80388.HK',
 '00120.HK',
 '02432.HK',
 '07234.HK',
 '02218.HK',
 '01899.HK',
 '09067.HK',
 '07299.HK',
 '06160.HK',
 '09669.HK',
 '06896.HK',
 '02848.HK',
 '03119.HK',
 '09860.HK',
 '02508.HK',
 '08406.HK',
 '01502.HK',
 '01997.HK',
 '02846.HK',
 '82846.HK',
 '02262.HK',
 '09195.HK',
 '03151.HK',
 '00240.HK',
 '03067.HK',
 '09846.HK',
 '09167.HK',
 '00099.HK',
 '00823.HK',
 '01666.HK',
 '00836.HK',
 '01945.HK',
 '01883.HK',
 '09699.HK',
 '09806.HK',
 '06060.HK',
 '03136.HK',
 '02838.HK',
 ...]

In [8]:
# —— 2. 定义时间区间和频率 —— 
start_date = "2025-07-01"
end_date   = "2025-08-01"
interval   = "1d"    # 日线

In [9]:
# 添加重试机制
# 安全下载收盘价函数
def safe_download_close(ticker, max_retries=1, wait_time=1):
    for attempt in range(max_retries):
        try:
            data = yf.download(
                tickers=ticker,
                start = start_date,
                end = end_date,      # 最近一年
                interval="1d",      # 日线
                progress=False,
                auto_adjust=True    # 自动复权
            )
            if not data.empty:
                # 只保留收盘价
                return data[['Close']]
        except Exception as e:
            print(f"[错误] {ticker} 第 {attempt+1}/{max_retries} 次尝试失败: {str(e)}")
        
        time.sleep(wait_time)
    
    print(f"[失败] 无法获取 {ticker} 的数据")
    return pd.DataFrame()


# 使用安全下载函数
ticker_symbol = "08025.HK"
stock_data = safe_download_close(ticker_symbol)

1 Failed download:
['08025.HK']: YFPricesMissingError('possibly delisted; no price data found  (1d 2025-07-01 -> 2025-08-01)')

[失败] 无法获取 08025.HK 的数据

In [10]:
stock_data

Empty DataFrame
Columns: []
Index: []

In [14]:
# 存储所有收盘价数据
all_close = pd.DataFrame()

In [12]:
tickers[1][1:]

'1667.HK'

In [ ]:
# 遍历下载
for ticker in tqdm(tickers, desc="下载港股收盘价"):
    if ticker.startswith("0"):
        ticker = ticker[1:]
    close_df = safe_download_close(ticker)
    if not close_df.empty:
        # 重命名列为股票代码
        close_df.rename(columns={"Close": ticker}, inplace=True)
        
        # 合并数据（按日期对齐）
        if all_close.empty:
            all_close = close_df
        else:
            all_close = all_close.join(close_df, how='outer')

In [15]:
tickers

['01152.HK',
 '01667.HK',
 '02442.HK',
 '08537.HK',
 '00202.HK',
 '08249.HK',
 '00602.HK',
 '01080.HK',
 '02400.HK',
 '01967.HK',
 '00767.HK',
 '00265.HK',
 '01228.HK',
 '01938.HK',
 '06113.HK',
 '08340.HK',
 '02415.HK',
 '00508.HK',
 '01237.HK',
 '02170.HK',
 '08223.HK',
 '01797.HK',
 '08100.HK',
 '02182.HK',
 '02427.HK',
 '02350.HK',
 '01812.HK',
 '00348.HK',
 '06998.HK',
 '08277.HK',
 '00323.HK',
 '01968.HK',
 '01672.HK',
 '06622.HK',
 '00093.HK',
 '02558.HK',
 '01428.HK',
 '02500.HK',
 '01432.HK',
 '01286.HK',
 '08366.HK',
 '08153.HK',
 '00568.HK',
 '06918.HK',
 '00865.HK',
 '00899.HK',
 '01631.HK',
 '09606.HK',
 '08176.HK',
 '01741.HK',
 '01947.HK',
 '02522.HK',
 '06855.HK',
 '08456.HK',
 '00075.HK',
 '02696.HK',
 '02168.HK',
 '00915.HK',
 '02340.HK',
 '08232.HK',
 '00983.HK',
 '01473.HK',
 '03728.HK',
 '00619.HK',
 '09968.HK',
 '01150.HK',
 '00799.HK',
 '08480.HK',
 '00326.HK',
 '02157.HK',
 '01020.HK',
 '09930.HK',
 '01877.HK',
 '08106.HK',
 '00320.HK',
 '08040.HK',
 '01022.HK',
 '02545.HK',
 '02616.HK',
 '00695.HK',
 '02310.HK',
 '00583.HK',
 '02162.HK',
 '08156.HK',
 '01676.HK',
 '06660.HK',
 '00557.HK',
 '02559.HK',
 '09788.HK',
 '06968.HK',
 '07788.HK',
 '03836.HK',
 '00422.HK',
 '01647.HK',
 '06996.HK',
 '00108.HK',
 '02066.HK',
 '06038.HK',
 '01500.HK',
 '00932.HK',
 '01661.HK',
 '00085.HK',
 '08059.HK',
 '02221.HK',
 '02216.HK',
 '02314.HK',
 '01675.HK',
 '01991.HK',
 '02100.HK',
 '08299.HK',
 '00376.HK',
 '00984.HK',
 '00846.HK',
 '01653.HK',
 '02552.HK',
 '00242.HK',
 '06058.HK',
 '00305.HK',
 '02567.HK',
 '06628.HK',
 '00547.HK',
 '08080.HK',
 '02142.HK',
 '09969.HK',
 '01304.HK',
 '02250.HK',
 '09799.HK',
 '02590.HK',
 '01940.HK',
 '01433.HK',
 '02012.HK',
 '00302.HK',
 '01132.HK',
 '00076.HK',
 '00200.HK',
 '02225.HK',
 '00587.HK',
 '00285.HK',
 '08645.HK',
 '00111.HK',
 '02181.HK',
 '00519.HK',
 '08222.HK',
 '00368.HK',
 '01712.HK',
 '01148.HK',
 '08021.HK',
 '01129.HK',
 '01801.HK',
 '08017.HK',
 '00880.HK',
 '02256.HK',
 '00086.HK',
 '06610.HK',
 '00259.HK',
 '00655.HK',
 '09939.HK',
 '00493.HK',
 '01763.HK',
 '07799.HK',
 '01250.HK',
 '01486.HK',
 '01900.HK',
 '00712.HK',
 '00434.HK',
 '02603.HK',
 '03603.HK',
 '01628.HK',
 '00876.HK',
 '00745.HK',
 '00230.HK',
 '03738.HK',
 '09926.HK',
 '01340.HK',
 '00497.HK',
 '08379.HK',
 '02110.HK',
 '01427.HK',
 '02122.HK',
 '00022.HK',
 '09869.HK',
 '06185.HK',
 '02689.HK',
 '00553.HK',
 '82388.HK',
 '01739.HK',
 '01167.HK',
 '09995.HK',
 '02410.HK',
 '00670.HK',
 '06609.HK',
 '00620.HK',
 '02033.HK',
 '01569.HK',
 '03395.HK',
 '06990.HK',
 '00717.HK',
 '02105.HK',
 '02388.HK',
 '08229.HK',
 '02298.HK',
 '01773.HK',
 '00496.HK',
 '01119.HK',
 '08238.HK',
 '08545.HK',
 '06119.HK',
 '01164.HK',
 '00521.HK',
 '06100.HK',
 '01272.HK',
 '02171.HK',
 '01916.HK',
 '06088.HK',
 '09688.HK',
 '00039.HK',
 '00027.HK',
 '08471.HK',
 '01062.HK',
 '03087.HK',
 '02126.HK',
 '80992.HK',
 '01655.HK',
 '01111.HK',
 '01530.HK',
 '00258.HK',
 '01621.HK',
 '09990.HK',
 '01172.HK',
 '00931.HK',
 '00992.HK',
 '00162.HK',
 '01541.HK',
 '87001.HK',
 '02804.HK',
 '00149.HK',
 '00995.HK',
 '01449.HK',
 '03046.HK',
 '01578.HK',
 '02185.HK',
 '02457.HK',
 '00095.HK',
 '00630.HK',
 '01128.HK',
 '03004.HK',
 '02668.HK',
 '02209.HK',
 '02722.HK',
 '02155.HK',
 '02509.HK',
 '00347.HK',
 '01903.HK',
 '01927.HK',
 '00613.HK',
 '01069.HK',
 '01776.HK',
 '09660.HK',
 '03908.HK',
 '02172.HK',
 '01097.HK',
 '01582.HK',
 '08540.HK',
 '09804.HK',
 '02425.HK',
 '01870.HK',
 '00999.HK',
 '01767.HK',
 '03068.HK',
 '03009.HK',
 '03301.HK',
 '03939.HK',
 '00777.HK',
 '00989.HK',
 '08071.HK',
 '00042.HK',
 '00306.HK',
 '06869.HK',
 '00405.HK',
 '01328.HK',
 '00856.HK',
 '02799.HK',
 '00581.HK',
 '09996.HK',
 '00727.HK',
 '03958.HK',
 '07261.HK',
 '00684.HK',
 '02728.HK',
 '09046.HK',
 '01629.HK',
 '03069.HK',
 '07766.HK',
 '06979.HK',
 '00682.HK',
 '09069.HK',
 '02235.HK',
 '02282.HK',
 '00998.HK',
 '03179.HK',
 '00366.HK',
 '08422.HK',
 '01708.HK',
 '00763.HK',
 '01093.HK',
 '03389.HK',
 '08631.HK',
 '02252.HK',
 '06127.HK',
 '01477.HK',
 '02455.HK',
 '00063.HK',
 '06613.HK',
 '02511.HK',
 '83046.HK',
 '00723.HK',
 '01208.HK',
 '06881.HK',
 '01988.HK',
 '02076.HK',
 '06929.HK',
 '03339.HK',
 '01651.HK',
 '06098.HK',
 '01112.HK',
 '01316.HK',
 '81299.HK',
 '00546.HK',
 '00710.HK',
 '07266.HK',
 '09680.HK',
 '02297.HK',
 '00329.HK',
 '00559.HK',
 '09626.HK',
 '03839.HK',
 '00726.HK',
 '00245.HK',
 '00107.HK',
 '01952.HK',
 '01508.HK',
 '06066.HK',
 '01456.HK',
 '02227.HK',
 '02643.HK',
 '01606.HK',
 '01238.HK',
 '03788.HK',
 '00968.HK',
 '09179.HK',
 '02228.HK',
 '00811.HK',
 '01177.HK',
 '01599.HK',
 '00691.HK',
 '00270.HK',
 '03174.HK',
 '03399.HK',
 '01216.HK',
 '00013.HK',
 '09009.HK',
 '01000.HK',
 '06682.HK',
 '02555.HK',
 '01299.HK',
 '01359.HK',
 '08163.HK',
 '01319.HK',
 '01526.HK',
 '00171.HK',
 '06839.HK',
 '00204.HK',
 '00425.HK',
 '08629.HK',
 '00576.HK',
 '00805.HK',
 '00871.HK',
 '01029.HK',
 '01725.HK',
 '00788.HK',
 '06818.HK',
 '03918.HK',
 '02236.HK',
 '08622.HK',
 '00697.HK',
 '06806.HK',
 '00950.HK',
 '00163.HK',
 '09900.HK',
 '01375.HK',
 '00152.HK',
 '07311.HK',
 '00272.HK',
 '09890.HK',
 '01476.HK',
 '01928.HK',
 '02680.HK',
 '00853.HK',
 '06199.HK',
 '02566.HK',
 '01064.HK',
 '02255.HK',
 '00862.HK',
 '02203.HK',
 '00327.HK',
 '02628.HK',
 '00081.HK',
 '02359.HK',
 '02866.HK',
 '00560.HK',
 '00675.HK',
 '01059.HK',
 '08128.HK',
 '02309.HK',
 '00863.HK',
 '00293.HK',
 '02137.HK',
 '08476.HK',
 '00595.HK',
 '00354.HK',
 '03709.HK',
 '00373.HK',
 '01263.HK',
 '00893.HK',
 '08519.HK',
 '00055.HK',
 '00894.HK',
 '08196.HK',
 '08429.HK',
 '01555.HK',
 '00317.HK',
 '09899.HK',
 '01288.HK',
 '01268.HK',
 '00952.HK',
 '02013.HK',
 '09959.HK',
 '02880.HK',
 '02772.HK',
 '01891.HK',
 '00010.HK',
 '02569.HK',
 '03158.HK',
 '00365.HK',
 '00383.HK',
 '00806.HK',
 '00346.HK',
 '02018.HK',
 '01905.HK',
 '03678.HK',
 '01113.HK',
 '03405.HK',
 '02778.HK',
 '09766.HK',
 '01075.HK',
 '01717.HK',
 '01568.HK',
 '02129.HK',
 '03931.HK',
 '06822.HK',
 '00321.HK',
 '01691.HK',
 '02601.HK',
 '03993.HK',
 '00048.HK',
 '02389.HK',
 '06196.HK',
 '00179.HK',
 '00757.HK',
 '09868.HK',
 '06955.HK',
 '09992.HK',
 '01257.HK',
 '00165.HK',
 '03132.HK',
 '00768.HK',
 '01488.HK',
 '83069.HK',
 '06939.HK',
 '01114.HK',
 '01698.HK',
 '06099.HK',
 '03360.HK',
 '08220.HK',
 '08612.HK',
 '00667.HK',
 '02283.HK',
 '03882.HK',
 '01786.HK',
 '06663.HK',
 '00028.HK',
 '00151.HK',
 '02820.HK',
 '01157.HK',
 '00718.HK',
 '01339.HK',
 '02007.HK',
 '00662.HK',
 '06178.HK',
 '00753.HK',
 '03396.HK',
 '09820.HK',
 '00598.HK',
 '06963.HK',
 '01053.HK',
 '02600.HK',
 '01733.HK',
 '00926.HK',
 '01419.HK',
 '09919.HK',
 '03347.HK',
 '02150.HK',
 '03056.HK',
 '00731.HK',
 '01102.HK',
 '02022.HK',
 '02660.HK',
 '02576.HK',
 '01816.HK',
 '01030.HK',
 '02239.HK',
 '01251.HK',
 '01280.HK',
 '00861.HK',
 '08423.HK',
 '00833.HK',
 '00884.HK',
 '08657.HK',
 '03650.HK',
 '06655.HK',
 '06608.HK',
 '00511.HK',
 '06639.HK',
 '01933.HK',
 '00322.HK',
 '01338.HK',
 '00119.HK',
 '02487.HK',
 '00640.HK',
 '01024.HK',
 '00290.HK',
 '02453.HK',
 '02208.HK',
 '00160.HK',
 '01368.HK',
 '02536.HK',
 '02886.HK',
 '03034.HK',
 '81024.HK',
 '00558.HK',
 '02232.HK',
 '03866.HK',
 '01527.HK',
 '08043.HK',
 '01276.HK',
 '09911.HK',
 '06198.HK',
 '00371.HK',
 '09698.HK',
 '02230.HK',
 '00345.HK',
 '06158.HK',
 '00467.HK',
 '02899.HK',
 '06030.HK',
 '08529.HK',
 '00157.HK',
 '03006.HK',
 '02016.HK',
 '00314.HK',
 '03454.HK',
 '03877.HK',
 '00900.HK',
 '01729.HK',
 '01398.HK',
 '02197.HK',
 '02551.HK',
 '01620.HK',
 '07233.HK',
 '01378.HK',
 '01496.HK',
 '02563.HK',
 '01060.HK',
 '00191.HK',
 '00535.HK',
 '00868.HK',
 '00211.HK',
 '01709.HK',
 '01833.HK',
 '00912.HK',
 '09989.HK',
 '03185.HK',
 '01963.HK',
 '03988.HK',
 '00732.HK',
 '02111.HK',
 '09922.HK',
 '01347.HK',
 '00683.HK',
 '01907.HK',
 '01610.HK',
 '02814.HK',
 '01617.HK',
 '03319.HK',
 '09676.HK',
 '83455.HK',
 '03328.HK',
 '02598.HK',
 '09074.HK',
 '00185.HK',
 '01662.HK',
 '01025.HK',
 '00970.HK',
 '08512.HK',
 '02342.HK',
 '01961.HK',
 '09814.HK',
 '02429.HK',
 '08371.HK',
 '00956.HK',
 '01071.HK',
 '01747.HK',
 '01730.HK',
 '01379.HK',
 '01756.HK',
 '00251.HK',
 '03692.HK',
 '00819.HK',
 '00631.HK',
 '00257.HK',
 '02507.HK',
 '03116.HK',
 '06188.HK',
 '03868.HK',
 '01908.HK',
 '01955.HK',
 '09893.HK',
 '01301.HK',
 '03306.HK',
 '01055.HK',
 '01085.HK',
 '09455.HK',
 '01523.HK',
 '08282.HK',
 '00169.HK',
 '02096.HK',
 '00752.HK',
 '01313.HK',
 '03074.HK',
 '02617.HK',
 '00363.HK',
 '03147.HK',
 '03686.HK',
 '02192.HK',
 '00517.HK',
 '03455.HK',
 '02858.HK',
 '06823.HK',
 '03938.HK',
 '02382.HK',
 '00590.HK',
 '03036.HK',
 '02167.HK',
 '01247.HK',
 '00177.HK',
 '08037.HK',
 '09834.HK',
 '03453.HK',
 '01848.HK',
 '09311.HK',
 '00564.HK',
 '00525.HK',
 '02138.HK',
 '00991.HK',
 '02339.HK',
 '00168.HK',
 '03898.HK',
 '06603.HK',
 '01788.HK',
 '00401.HK',
 '06601.HK',
 '00144.HK',
 '02459.HK',
 '06669.HK',
 '00626.HK',
 '00855.HK',
 '01133.HK',
 '02376.HK',
 '00822.HK',
 '01141.HK',
 '00951.HK',
 '03838.HK',
 '00551.HK',
 '00808.HK',
 '01995.HK',
 '06812.HK',
 '00743.HK',
 '00616.HK',
 '02233.HK',
 '02810.HK',
 '02834.HK',
 '82020.HK',
 '00201.HK',
 '02356.HK',
 '03718.HK',
 '00677.HK',
 '09086.HK',
 '01898.HK',
 '07262.HK',
 '03382.HK',
 '01529.HK',
 '02347.HK',
 '08611.HK',
 '03171.HK',
 '01138.HK',
 '03086.HK',
 '03669.HK',
 '02518.HK',
 '80700.HK',
 '00591.HK',
 '09159.HK',
 '80020.HK',
 '00440.HK',
 '02097.HK',
 '01521.HK',
 '03442.HK',
 '00148.HK',
 '01799.HK',
 '03172.HK',
 '01393.HK',
 '09991.HK',
 '01836.HK',
 '00556.HK',
 '00610.HK',
 '01317.HK',
 '02888.HK',
 '00966.HK',
 '01751.HK',
 '00459.HK',
 '00358.HK',
 '01033.HK',
 '00656.HK',
 '01880.HK',
 '00023.HK',
 '09658.HK',
 '03195.HK',
 '02586.HK',
 '00116.HK',
 '01072.HK',
 '02465.HK',
 '00510.HK',
 '01766.HK',
 '06666.HK',
 '09987.HK',
 '82830.HK',
 '06868.HK',
 '03759.HK',
 '00227.HK',
 '02031.HK',
 '00412.HK',
 '03412.HK',
 '02015.HK',
 '02482.HK',
 '01088.HK',
 '01083.HK',
 '02263.HK',
 '00939.HK',
 '02020.HK',
 '02251.HK',
 '07200.HK',
 '02688.HK',
 '03618.HK',
 '02368.HK',
 '03134.HK',
 '02009.HK',
 '01001.HK',
 '02411.HK',
 '01873.HK',
 '00241.HK',
 '02269.HK',
 '02331.HK',
 '02319.HK',
 '09896.HK',
 '03156.HK',
 '01718.HK',
 '07226.HK',
 '82331.HK',
 '08160.HK',
 '01258.HK',
 '01860.HK',
 '09107.HK',
 '00267.HK',
 '09156.HK',
 '01273.HK',
 '00700.HK',
 '06138.HK',
 '02699.HK',
 '02570.HK',
 '03698.HK',
 '01499.HK',
 '00229.HK',
 '00300.HK',
 '01373.HK',
 '00392.HK',
 '03969.HK',
 '09999.HK',
 '03165.HK',
 '02328.HK',
 '00882.HK',
 '02377.HK',
 '00588.HK',
 '09181.HK',
 '01057.HK',
 '01650.HK',
 '03606.HK',
 '03998.HK',
 '00038.HK',
 '03181.HK',
 '01516.HK',
 '00008.HK',
 '01909.HK',
 '09810.HK',
 '82823.HK',
 '09747.HK',
 '02877.HK',
 '00123.HK',
 '02878.HK',
 '00754.HK',
 '03150.HK',
 '06886.HK',
 '01601.HK',
 '02823.HK',
 '03383.HK',
 '02506.HK',
 '00001.HK',
 '83111.HK',
 '06862.HK',
 '03363.HK',
 '00775.HK',
 '00315.HK',
 '03110.HK',
 '00294.HK',
 '01186.HK',
 '01920.HK',
 '01050.HK',
 '03470.HK',
 '01364.HK',
 '01052.HK',
 '02279.HK',
 '03896.HK',
 '83146.HK',
 '09070.HK',
 '08188.HK',
 '09686.HK',
 '00312.HK',
 '07288.HK',
 '00037.HK',
 '09839.HK',
 '09979.HK',
 '08027.HK',
 '03021.HK',
 '01895.HK',
 '08219.HK',
 '00536.HK',
 '00696.HK',
 '06676.HK',
 '02338.HK',
 '00450.HK',
 '00611.HK',
 '09446.HK',
 '03190.HK',
 '03020.HK',
 '01713.HK',
 '01481.HK',
 '02801.HK',
 '00533.HK',
 '01308.HK',
 '00390.HK',
 '03410.HK',
 '83189.HK',
 '01823.HK',
 '06093.HK',
 '83403.HK',
 '03182.HK',
 '09146.HK',
 '86618.HK',
 '02257.HK',
 '03601.HK',
 '03153.HK',
 '02381.HK',
 '02839.HK',
 '82839.HK',
 '09668.HK',
 '03318.HK',
 '02386.HK',
 '01330.HK',
 '00772.HK',
 '83168.HK',
 '82822.HK',
 '02806.HK',
 '06618.HK',
 '00653.HK',
 '83188.HK',
 '03432.HK',
 '01278.HK',
 '01910.HK',
 '02727.HK',
 '00215.HK',
 '00909.HK',
 '02843.HK',
 '83010.HK',
 '03189.HK',
 '03422.HK',
 '03443.HK',
 '03145.HK',
 '02038.HK',
 '83038.HK',
 '01855.HK',
 '80175.HK',
 '08495.HK',
 '01681.HK',
 '00689.HK',
 '01668.HK',
 '09923.HK',
 '09887.HK',
 '03111.HK',
 '03188.HK',
 '03413.HK',
 '03003.HK',
 '01658.HK',
 '01410.HK',
 '01999.HK',
 '09403.HK',
 '03368.HK',
 '02803.HK',
 '02830.HK',
 '01475.HK',
 '00435.HK',
 '01415.HK',
 '03039.HK',
 '01066.HK',
 '01532.HK',
 '03433.HK',
 '09803.HK',
 '09115.HK',
 '03040.HK',
 '03029.HK',
 '03070.HK',
 '00552.HK',
 '82843.HK',
 '03800.HK',
 '09188.HK',
 '01635.HK',
 '02068.HK',
 '06969.HK',
 '09633.HK',
 '01448.HK',
 '08050.HK',
 '00728.HK',
 '02571.HK',
 '03033.HK',
 '03012.HK',
 '80388.HK',
 '00120.HK',
 '02432.HK',
 '07234.HK',
 '02218.HK',
 '01899.HK',
 '09067.HK',
 '07299.HK',
 '06160.HK',
 '09669.HK',
 '06896.HK',
 '02848.HK',
 '03119.HK',
 '09860.HK',
 '02508.HK',
 '08406.HK',
 '01502.HK',
 '01997.HK',
 '02846.HK',
 '82846.HK',
 '02262.HK',
 '09195.HK',
 '03151.HK',
 '00240.HK',
 '03067.HK',
 '09846.HK',
 '09167.HK',
 '00099.HK',
 '00823.HK',
 '01666.HK',
 '00836.HK',
 '01945.HK',
 '01883.HK',
 '09699.HK',
 '09806.HK',
 '06060.HK',
 '03136.HK',
 '02838.HK',
 ...]

In [17]:
all_close

Price,1152.HK,1667.HK,2442.HK,8537.HK,0202.HK,8249.HK,0602.HK,1080.HK,2400.HK,1967.HK,...,0286.HK,0279.HK,0274.HK,0223.HK,0195.HK,0176.HK,0102.HK,0059.HK,0009.HK,0007.HK
Ticker,1152.HK,1667.HK,2442.HK,8537.HK,0202.HK,8249.HK,0602.HK,1080.HK,2400.HK,1967.HK,...,0286.HK,0279.HK,0274.HK,0223.HK,0195.HK,0176.HK,0102.HK,0059.HK,0009.HK,0007.HK
Date,,,,,,,,,,,,,,,,,,,,,
2025-07-02,0.073,0.13,1.30,0.167,0.055,0.139,0.040,0.038,49.000000,0.405,...,1.31,0.92,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-03,0.073,0.13,1.35,0.180,0.055,0.138,0.043,0.037,48.400002,0.400,...,1.31,0.82,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-04,0.073,0.13,1.37,0.187,0.058,0.138,0.044,0.039,49.849998,0.385,...,1.31,0.78,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-07,0.073,0.13,1.38,0.187,0.058,0.098,0.044,0.037,51.000000,0.340,...,1.31,0.80,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-08,0.073,0.13,1.38,0.170,0.058,0.100,0.044,0.040,51.299999,0.355,...,1.31,0.80,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-09,0.073,0.13,1.42,0.170,0.057,0.100,0.044,0.042,50.900002,0.395,...,1.31,0.84,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-10,0.073,0.13,1.42,0.169,0.060,0.100,0.044,0.060,50.049999,0.465,...,1.31,0.82,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-11,0.073,0.13,1.42,0.171,0.059,0.102,0.044,0.054,48.849998,0.485,...,1.31,0.86,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-14,0.073,0.13,1.40,0.175,0.058,0.102,0.039,0.055,50.099998,0.495,...,1.31,0.88,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-15,0.073,0.13,1.38,0.175,0.058,0.121,0.039,0.054,50.099998,0.445,...,1.31,0.84,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-16,0.073,0.13,1.34,0.175,0.058,0.116,0.039,0.057,51.000000,0.465,...,1.31,0.84,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-17,0.073,0.13,1.36,0.174,0.056,0.116,0.038,0.063,50.950001,0.485,...,1.31,0.80,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-18,0.073,0.13,1.36,0.175,0.056,0.116,0.038,0.060,51.299999,0.490,...,1.31,0.88,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-21,0.073,0.13,1.36,0.175,0.055,0.118,0.038,0.056,51.900002,0.455,...,1.31,0.90,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-22,0.073,0.13,1.40,0.175,0.056,0.125,0.048,0.056,51.400002,0.470,...,1.31,0.88,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-23,0.073,0.13,1.42,0.176,0.058,0.133,0.054,0.059,52.200001,0.480,...,1.31,0.88,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-24,0.073,0.13,1.50,0.176,0.057,0.121,0.053,0.059,51.299999,0.470,...,1.31,0.88,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-25,0.073,0.13,1.55,0.177,0.059,0.124,0.051,0.058,51.849998,0.480,...,1.31,0.88,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-28,0.073,0.13,1.57,0.192,0.056,0.157,0.052,0.057,50.900002,0.475,...,1.31,0.88,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-29,0.073,0.13,1.56,0.177,0.059,0.182,0.060,0.057,53.250000,0.475,...,1.31,0.88,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-30,0.073,0.13,1.60,0.189,0.059,0.180,0.054,0.062,53.200001,0.470,...,1.31,0.87,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032
2025-07-31,0.073,0.13,1.55,0.160,0.059,0.180,0.054,0.069,52.400002,0.450,...,1.31,0.90,0.49,0.109,0.285,0.013,0.047,0.01,0.013,0.032

In [19]:
all_close = all_close.T

In [21]:
all_close.to_csv('../data/hongkong.csv')

# 获取A股

In [3]:
lg = bs.login()
if lg.error_code != "0":
    raise RuntimeError("登录失败：" + lg.error_msg)

# 2. 拉取证券基本资料（只需要 code 和 name，也可以带其他列）
rs = bs.query_stock_basic()
# 把结果逐条读到列表里
data_list = []
while rs.error_code == '0' and rs.next():
    data_list.append(rs.get_row_data())

# 3. 转成 DataFrame，并清理列名空格
df = pd.DataFrame(data_list, columns=rs.fields)
df.columns = [c.strip() for c in df.columns]

print("所有证券样例：")
print(df.head(), "\n", df.columns.tolist())

# 4. 只保留 A 股股票
#    type == '1' 表示“股票”；status == '1' 表示“在市”
df_a = df[(df['type']   == '1') &
          (df['status'] == '1')].reset_index(drop=True)

print(f"共计 {len(df_a)} 只在市的 A 股")
print(df_a.head())

bs.logout()

login success!
所有证券样例：
        code code_name     ipoDate outDate type status
0  sh.000001    上证综合指数  1991-07-15            2      1
1  sh.000002    上证A股指数  1992-02-21            2      1
2  sh.000003    上证B股指数  1992-08-17            2      1
3  sh.000004   上证工业类指数  1993-05-03            2      1
4  sh.000005   上证商业类指数  1993-05-03            2      1
 ['code', 'code_name', 'ipoDate', 'outDate', 'type', 'status']
共计 5183 只在市的 A 股
        code code_name     ipoDate outDate type status
0  sh.600000      浦发银行  1999-11-10            1      1
1  sh.600004      白云机场  2003-04-28            1      1
2  sh.600006      东风股份  1999-07-27            1      1
3  sh.600007      中国国贸  1999-03-12            1      1
4  sh.600008      首创环保  2000-04-27            1      1
logout success!

In [ ]:
df_a = df_a['code'].tolist()

In [ ]:
df_a

In [5]:
# 3. 定义拉取区间
start_date = "2023-07-01"
end_date   = "2023-08-31"

records = []
batch_size = 1   # 每1只重连一次

for i, code in enumerate(tqdm(df_a, desc="拉取收盘价")):
    # 每 batch_size 只断开并重连一次
    if i and i % batch_size == 0:
        bs.logout()
        time.sleep(0.1)      # 等待底层完全断开
        bs.login()         # 重新登录

    # 拉取并重试
    for attempt in range(3):
        try:
            rs = bs.query_history_k_data_plus(
                code,
                "date,close",
                start_date=start_date,
                end_date=end_date,
                frequency="d",
                adjustflag="3"
            )
            df = rs.get_data()
            if not df.empty:
                df["code"] = code
                records.append(df)
            break
        except Exception as e:
            print(f"[{code}] 第 {attempt+1} 次失败：{e}，等待后重试")
            time.sleep(0.1)
    time.sleep(0.1)  # **1 秒/只**，极限限速

# 4. 合并 & pivot
df_result = pd.concat(records, ignore_index=True)
df_wide = df_result.pivot(index="code", columns="date", values="close")
df_wide.columns = [pd.to_datetime(d).strftime("%m-%d")
                   for d in df_wide.columns]

拉取收盘价:   0%|          | 1/5183 [00:00<08:43,  9.89it/s]

股票代码应为9位，请检查。格式示例：sh.600000。
logout success!

拉取收盘价:   0%|          | 2/5183 [00:01<58:07,  1.49it/s]

login success!
logout success!

拉取收盘价:   0%|          | 3/5183 [00:01<58:23,  1.48it/s]

login success!
股票代码应为9位，请检查。格式示例：sh.600000。
logout success!
login success!
股票代码应为9位，请检查。格式示例：sh.600000。

拉取收盘价:   0%|          | 4/5183 [00:02<57:57,  1.49it/s]

logout success!
login success!
股票代码应为9位，请检查。格式示例：sh.600000。

拉取收盘价:   0%|          | 5/5183 [00:02<48:08,  1.79it/s]

logout success!
login success!
股票代码应为9位，请检查。格式示例：sh.600000。

拉取收盘价:   0%|          | 6/5183 [00:03<48:43,  1.77it/s]

ValueError: No objects to concatenate

In [ ]:
df_wide.to_csv('../data/data.csv')

In [ ]:
# 5. 登出
bs.logout()

# 获取A股单只股票价格

In [20]:
# 光线传媒：300251.SZ
df = yf.download("300251.SZ",
                 start="2025-01-14",
                 end="2025-02-18",   # end为开区间，写到次日以包含 02-17
                 interval="1d",
                 progress=False)

print(df["Close"])  # 每天的收盘价

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4064\1028534116.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download("300251.SZ",

Ticker      300251.SZ
Date
2025-01-14   8.890718
2025-01-15   8.801711
2025-01-16   8.841269
2025-01-17   9.197294
2025-01-20   9.276411
2025-01-21   9.256632
2025-01-22   9.335748
2025-01-23   9.414865
2025-01-24   9.395085
2025-01-27   9.424754
2025-02-05  11.313661
2025-02-06  13.350911
2025-02-07  13.805831
2025-02-10  16.565020
2025-02-11  19.878023
2025-02-12  23.853628
2025-02-13  28.620398
2025-02-14  34.346455
2025-02-17  29.332447

In [21]:
df = df["Close"]
df.to_csv('../data/nezha.csv',index=False)